// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCktzP7l-BUuYuhKUKHlvVMnnI9oqzHiQ',
    appId: '1:881101564216:web:1b0fb05494fbd9e78979cd',
    messagingSenderId: '881101564216',
    projectId: 'expence-tracker-app-f5590',
    authDomain: 'expence-tracker-app-f5590.firebaseapp.com',
    storageBucket: 'expence-tracker-app-f5590.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPhRPLqlinP1KxMJ-OJIIDLyvKNFPVty0',
    appId: '1:881101564216:android:1d421c7f163ac1328979cd',
    messagingSenderId: '881101564216',
    projectId: 'expence-tracker-app-f5590',
    storageBucket: 'expence-tracker-app-f5590.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtgKQLC8pWAAvzlgCyBCS_jPK8Ixch-Bg',
    appId: '1:881101564216:ios:09b6b293237d785d8979cd',
    messagingSenderId: '881101564216',
    projectId: 'expence-tracker-app-f5590',
    storageBucket: 'expence-tracker-app-f5590.firebasestorage.app',
    iosBundleId: 'com.example.expenceTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtgKQLC8pWAAvzlgCyBCS_jPK8Ixch-Bg',
    appId: '1:881101564216:ios:09b6b293237d785d8979cd',
    messagingSenderId: '881101564216',
    projectId: 'expence-tracker-app-f5590',
    storageBucket: 'expence-tracker-app-f5590.firebasestorage.app',
    iosBundleId: 'com.example.expenceTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCktzP7l-BUuYuhKUKHlvVMnnI9oqzHiQ',
    appId: '1:881101564216:web:4fb98f90f15e8edc8979cd',
    messagingSenderId: '881101564216',
    projectId: 'expence-tracker-app-f5590',
    authDomain: 'expence-tracker-app-f5590.firebaseapp.com',
    storageBucket: 'expence-tracker-app-f5590.firebasestorage.app',
  );

}